# MinIO Configuration for LGTM Stack
mode: standalone

# Credentials
rootUser: minioadmin
rootPassword: minioadmin123

# Resources
resources:
  requests:
    memory: 512Mi
    cpu: 250m
  limits:
    memory: 1Gi
    cpu: 500m

# Persistence
persistence:
  enabled: true
  size: 20Gi
  storageClass: local-path

# Service
service:
  type: ClusterIP
  port: 9000

# Console (MinIO UI)
consoleService:
  type: ClusterIP
  port: 9001

# Buckets to create automatically
buckets:
  - name: loki-chunks
    policy: none
    purge: false
  - name: loki-ruler
    policy: none
    purge: false
  - name: tempo-traces
    policy: none
    purge: false
  - name: mimir-blocks
    policy: none
    purge: false
  - name: mimir-ruler
    policy: none
    purge: false
  - name: mimir-alertmanager
    policy: none
    purge: false

# Users (optional)
users: []

# Policies (optional)  
policies: []

# Disable default console ingress
ingress:
  enabled: false
consoleIngress:
  enabled: false