# OpenTelemetry Instrumentation CRD - Auto-instrumentation
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: default-instrumentation
  namespace: opentelemetry-operator-system
spec:
  # Exporter configuration - where to send traces
  exporter:
    endpoint: http://otel-collector-collector.monitoring.svc.cluster.local:4317
  
  # Propagation formats
  propagators:
    - tracecontext
    - baggage
    - b3
  
  # Sampling configuration
  sampler:
    type: parentbased_traceidratio
    argument: "0.25"  # 25% sampling rate
  
  # Resource attributes
  resource:
    addK8sUIDAttributes: true
  
  # Language-specific configurations
  java:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:latest
    env:
      - name: OTEL_JAVAAGENT_DEBUG
        value: "false"
      - name: OTEL_INSTRUMENTATION_JDBC_ENABLED
        value: "true"
      - name: OTEL_INSTRUMENTATION_KAFKA_ENABLED
        value: "true"
  
  nodejs:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:latest
    env:
      - name: OTEL_NODE_DEBUG
        value: "false"
  
  python:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python:latest
    env:
      - name: OTEL_PYTHON_DEBUG
        value: "false"
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: "http/protobuf"
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "http://otel-collector-collector.monitoring.svc.cluster.local:4318"
  
  dotnet:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-dotnet:latest
    env:
      - name: OTEL_DOTNET_DEBUG
        value: "false"