# Grafana Mimir Distributed Configuration
fullnameOverride: mimir

mimir:
  structuredConfig:
    multitenancy_enabled: false
    
    blocks_storage:
      backend: filesystem
      filesystem:
        dir: /data/blocks
        
    ruler_storage:
      backend: filesystem
      filesystem:
        dir: /data/ruler

    alertmanager_storage:
      backend: filesystem
      filesystem:
        dir: /data/alertmanager

# Minimal replicas for development
distributor:
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

ingester:
  replicas: 1
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 200m
      memory: 512Mi
  persistentVolume:
    enabled: true
    size: 10Gi
  zoneAwareReplication:
    enabled: false

querier:
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

query_frontend:
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

store_gateway:
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 256Mi
  persistentVolume:
    enabled: true
    size: 10Gi
  zoneAwareReplication:
    enabled: false

compactor:
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 256Mi
  persistentVolume:
    enabled: true
    size: 10Gi

# Disable components not needed for basic setup
ruler:
  enabled: false
alertmanager:
  enabled: false

# Monitoring
metaMonitoring:
  serviceMonitor:
    enabled: true