# Grafana Loki Configuration - SimpleScalable for production-ready setup
deploymentMode: SimpleScalable

loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: 's3'
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
    s3:
      endpoint: http://minio.minio.svc.cluster.local:9000
      accessKeyId: minioadmin
      secretAccessKey: minioadmin123
      s3ForcePathStyle: true
      insecure: true
  schemaConfig:
    configs:
    - from: "2024-01-01"
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: loki_index_
        period: 24h
  limits_config:
    ingestion_rate_mb: 4
    ingestion_burst_size_mb: 6
    max_streams_per_user: 10000
    max_line_size: 256KB
    retention_period: 24h
    max_query_parallelism: 16
    max_concurrent_tail_requests: 10
  # Enable tracing
  tracing:
    enabled: true
    jaeger:
      endpoint: http://otel-collector-collector.monitoring.svc.cluster.local:14268/api/traces
      sampler_type: const
      sampler_param: 1

chunksCache:
  enable: true
  allocatedMemory: 512
  maxItemMemory: 1
  writebackSizeLimit: 125MB

# Read components
read:
  replicas: 1
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi

# Write components  
write:
  replicas: 1
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi
  persistence:
    enabled: true
    size: 2Gi

# Backend (compactor, ruler, etc)
backend:
  replicas: 1
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 25m
      memory: 64Mi
  persistence:
    enabled: true
    size: 1Gi

# Gateway (nginx)
gateway:
  enabled: true
  replicas: 1
  resources:
    limits:
      cpu: 50m
      memory: 64Mi
    requests:
      cpu: 10m
      memory: 32Mi

test:
  enabled: false

monitoring:
  selfMonitoring:
    enabled: false
  serviceMonitor:
    enabled: true
    labels:
      release: kube-prometheus-stack